//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CosmeticSolutionSystemEntities : DbContext
    {
        [Obsolete("이거 쓰면 나쁜 놈")]
        public CosmeticSolutionSystemEntities()
            : base("name=CosmeticSolutionSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SalesLine> SalesLines { get; set; }
        public virtual DbSet<재무제표> 재무제표 { get; set; }
        public virtual DbSet<SalesStat> SalesStats { get; set; }
        public virtual DbSet<SalesVeganBrand> SalesVeganBrands { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
    }
}
