//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CosmeticSolutionSystemEntities : DbContext
    {
        public CosmeticSolutionSystemEntities()
            : base("name=CosmeticSolutionSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SalesLine> SalesLines { get; set; }
        public virtual DbSet<재무제표> 재무제표 { get; set; }
        public virtual DbSet<SalesEdit> SalesEdits { get; set; }
        public virtual DbSet<SalesStatistic> SalesStatistics { get; set; }
        public virtual DbSet<SalesVeganBrand> SalesVeganBrands { get; set; }
    }
}
