//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticSolutionSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStatistic
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> SalesTotal { get; set; }
    }
}
